schema:
  - schema.graphqls

exec:
  filename: generated.go
  package: graph

model:
  filename: model/models_gen.go
  package: model

resolver:
  layout: follow-schema
  dir: .
  package: graph
  filename_template: "{name}.resolvers.go"

autobind:
  - "github.com/Natayoane/go-clean-architecture/internal/infra/graph/model"

models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32 