### Create a new order
POST http://localhost:8000/order
Content-Type: application/json

{
    "id": "2",
    "price": 10.0,
    "tax": 1.0
}

### List all orders
GET http://localhost:8000/order
Content-Type: application/json
